### PR TITLE
fix(model): move name and version out of updated model info message struct

### PR DESCRIPTION
**Pull request by Phelan164**
Because

- Model name and version is not allowed to update

This commit

- Move model name and version out of updated model info message struct

### CODE REVIEW

**Comment by bochengyang** [comment]
@Phelan164 I would like to suggest another way of the design of protobuf like [this](https://github.com/instill-ai/protobufs/blob/main/pipeline/pipeline.proto#L50-L55)

```proto
rpc UpdatePipeline (UpdatePipelineRequest) returns (PipelineInfo) {
  option (google.api.http) = {
    patch: "/pipelines/{pipeline.name}"
    body: "pipeline"
  };
}
```

**Comment by Phelan164** [comment]
@bochengyang I agree that we could use ModelInfo for updating. But there is some fields in ModelInfo do not allow to be updated. So I create an other message struct for updating model info.

**Review by bochengyang — APPROVED** [review]
LGTM 🚀

**Comment by Phelan164** [comment]
@bochengyang I got your point. It is elegant way. I updated following that

**Pull request merged**
